INSERT INTO [Book] ([Title], [Author], [Description])
VALUES
('1984', 'George Orwell', '1984 est un roman politique dystopique de George Orwell publié en 1949.'),
('Le Meilleur des mondes', 'Aldous Huxley', 'Le Meilleur des mondes est un roman dystopique écrit en 1931 par Aldous Huxley.'),
('Le seigneur des anneaux', 'J.R.R. Tolkien', 'Le Seigneur des anneaux est un roman de fantasy épique de J. R. R. Tolkien.'),
('Harry Potter et la pierre philosophale', 'J.K. Rowling', 'Harry Potter à l''école des sorciers est le premier roman de la série littéraire centrée sur le personnage de Harry Potter créé par J. K. Rowling.'),
('Fondation', 'Isaac Asimov', 'Fondation est un roman de science-fiction écrit par Isaac Asimov.'),
('Dune', 'Frank Herbert', 'Dune est un roman de science-fiction écrit par Frank Herbert.'),
('L''Odyssée', 'Homère', 'L''Odyssée est un poème épique grec antique attribué à Homère.'),
('Les Misérables', 'Victor Hugo', 'Les Misérables est un roman historique de Victor Hugo publié en 1862.'),
('Le Comte de Monte-Cristo', 'Alexandre Dumas', 'Le Comte de Monte-Cristo est un roman d''aventure et de vengeance écrit par Alexandre Dumas.'),
('Germinal', 'Emile Zola', 'Germinal est un roman social d''Émile Zola, publié en 1885.'),
('Bel-Ami', 'Guy de Maupassant', 'Bel-Ami est un roman de Guy de Maupassant publié en 1885.'),
('La Horde du Contrevent', 'Alain Damasio', 'La Horde du Contrevent est un roman de science-fiction d''Alain Damasio paru en 2004.'),
('Le Parfum', 'Patrick Süskind', 'Le Parfum est un roman de Patrick Süskind publié en 1985.'),
('L''étranger', 'Albert Camus', 'L''Étranger est un roman d''Albert Camus publié en 1942.'),
('Les Fleurs du mal', 'Charles Baudelaire', 'Les Fleurs du mal est un recueil de poèmes de Charles Baudelaire, publié en 1857.'),
('Voyage au centre de la Terre', 'Jules Verne', 'Voyage au centre de la Terre est un roman d''aventures de Jules Verne publié en 1864.'),
('Madame Bovary', 'Gustave Flaubert', 'Madame Bovary est un roman de Gustave Flaubert publié en 1857.'),
('Les Trois Mousquetaires', 'Alexandre Dumas', 'Les Trois Mousquetaires est un roman historique d''Alexandre Dumas publié en 1844.'),
('Le Rouge et le Noir', 'Stendhal', 'Le Rouge et le Noir est un roman de Stendhal publié en 1830.'),
('Les Liaisons dangereuses', 'Pierre Choderlos de Laclos', 'Les Liaisons dangereuses est un roman épistolaire de Pierre Choderlos de Laclos publié en 1782.'),
('La Peste', 'Albert Camus', 'La Peste est un roman d''Albert Camus publié en 1947.'),
('La Promesse de l''aube', 'Romain Gary', 'La Promesse de l''aube est un roman autobiographique de Romain Gary publié en 1960.')